server:
  port: 9002
spring:
  application:
    name: analysis-service
  datasource:
    url: jdbc:mysql://localhost:3306/running_information_analysis_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

      update
      create_and_drop